#!/usr/bin/env node
// Build levelcode-ai for the browser: ONE file the web extension host can evaluate, plus the
// files the manifest points at. The desktop extension stays plain JS with no build step; this
// bundler only exists for the browser edition and writes nothing into extensions/.
//
//   node web/ai-extension/build.mjs --out <dir> --vscode <Code-OSS checkout> [--minify]
//
// Output (<dir>/levelcode-ai):  package.json (+ "browser"), extension.web.js, media/, README.md
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..', '..');
const SRC = path.join(REPO, 'extensions', 'levelcode-ai');

const args = Object.fromEntries(process.argv.slice(2).reduce((a, v, i, all) => {
	if (v.startsWith('--')) { a.push([v.slice(2), all[i + 1] && !all[i + 1].startsWith('--') ? all[i + 1] : 'true']); }
	return a;
}, []));
const outRoot = path.resolve(args.out || path.join(REPO, 'dist-web', 'extensions'));
const vscodeDir = path.resolve(args.vscode || path.join(REPO, 'vscode'));
const minify = args.minify === 'true';

/** Find esbuild and the `buffer` package in the Code-OSS checkout, which already depends on both. */
function locate(name, bases) {
	for (const b of bases) {
		try { return createRequire(path.join(b, 'noop.js')).resolve(name); } catch { /* next */ }
	}
	return null;
}
const esbuildEntry = locate('esbuild', [path.join(vscodeDir, 'build'), path.join(vscodeDir, 'extensions'), vscodeDir, REPO]);
if (!esbuildEntry) { console.error('esbuild not found under ' + vscodeDir + ' (run scripts/bootstrap.sh first)'); process.exit(2); }
const esbuild = await import(esbuildEntry);
const nodePaths = [path.join(vscodeDir, 'node_modules'), path.join(vscodeDir, 'build', 'node_modules')].filter((p) => fs.existsSync(p));
if (!nodePaths.some((p) => fs.existsSync(path.join(p, 'buffer')))) { console.error('the "buffer" package is missing from ' + vscodeDir + '/node_modules'); process.exit(2); }

const outDir = path.join(outRoot, 'levelcode-ai');
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

/* ----- the extension's own files, embedded so synchronous reads keep working ------------------ */
const TEXT = new Set(['.html', '.svg', '.md', '.json', '.css', '.js', '.txt']);
function collect(rel, filter) {
	const out = {};
	const walk = (dir) => {
		for (const e of fs.readdirSync(path.join(SRC, dir), { withFileTypes: true })) {
			const r = path.posix.join(dir, e.name);
			if (e.isDirectory()) { walk(r); continue; }
			if (filter && !filter(r)) { continue; }
			const buf = fs.readFileSync(path.join(SRC, r));
			out[r] = TEXT.has(path.extname(r)) ? buf.toString('utf8') : { base64: buf.toString('base64') };
		}
	};
	if (fs.existsSync(path.join(SRC, rel))) { walk(rel); }
	return out;
}
const assets = Object.assign({},
	collect('media'),
	collect('skills'),
	collect('diagram', (r) => r.endsWith('.js')),
);
const generated = path.join(HERE, 'assets.generated.js');
fs.writeFileSync(generated, '// GENERATED by build.mjs — do not edit, do not commit.\nmodule.exports = ' + JSON.stringify(assets) + ';\n');

/* ----- __dirname has no meaning in a bundle: point it at the mounted copy -------------------- */
const dirnamePlugin = {
	name: 'levelcode-dirname',
	setup(b) {
		b.onLoad({ filter: /extensions[\\/]levelcode-ai[\\/].*\.js$/ }, (a) => {
			let text = fs.readFileSync(a.path, 'utf8');
			if (!/\b__dirname\b/.test(text)) { return null; }
			const rel = path.relative(SRC, path.dirname(a.path)).split(path.sep).join('/');
			text = text.replace(/\b__dirname\b/g, `(globalThis.__lcExtPath + ${JSON.stringify(rel ? '/' + rel : '')})`);
			return { contents: text, loader: 'js' };
		});
	},
};

const shim = (n) => path.join(HERE, 'shims', n + '.js');
await esbuild.build({
	entryPoints: [path.join(HERE, 'entry.js')],
	outfile: path.join(outDir, 'extension.web.js'),
	bundle: true,
	platform: 'browser',
	format: 'cjs',
	target: 'es2022',
	external: ['vscode'],
	alias: {
		fs: shim('fs'), 'node:fs': shim('fs'),
		path: shim('path'), 'node:path': shim('path'),
		os: shim('os'), 'node:os': shim('os'),
		crypto: shim('crypto'), 'node:crypto': shim('crypto'),
		child_process: shim('child_process'), 'node:child_process': shim('child_process'),
	},
	inject: [path.join(HERE, 'inject.js')],
	define: { global: 'globalThis' },
	nodePaths,
	plugins: [dirnamePlugin],
	minify,
	sourcemap: minify ? false : 'inline',
	legalComments: 'none',
	logLevel: 'info',
});
fs.rmSync(generated, { force: true });

/* ----- manifest + the files it refers to ---------------------------------------------------- */
const pkg = JSON.parse(fs.readFileSync(path.join(SRC, 'package.json'), 'utf8'));
pkg.browser = './extension.web.js';
fs.writeFileSync(path.join(outDir, 'package.json'), JSON.stringify(pkg, null, '\t') + '\n');
for (const f of ['README.md', 'package.nls.json']) { if (fs.existsSync(path.join(SRC, f))) { fs.copyFileSync(path.join(SRC, f), path.join(outDir, f)); } }
fs.cpSync(path.join(SRC, 'media'), path.join(outDir, 'media'), { recursive: true });

const size = fs.statSync(path.join(outDir, 'extension.web.js')).size;
console.log(`levelcode-ai (browser) -> ${outDir}  extension.web.js ${(size / 1024).toFixed(0)} KB, ${Object.keys(assets).length} embedded files`);
